DROP DATABASE IF EXISTS eatDaBurger;
CREATE DATABASE eatDaBurger;
USE eatDaBurger;

CREATE TABLE burgerLog(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
devoured BOOLEAN DEFAULT false
);

SELECT * FROM burgerLog;